[[entries]]
id = "363e049b-c6b5-405a-b6f6-b1728fb99275"
type = "fix"
description = "hugo: Hugo now respects the baseUrl option @Heiss"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/233"

[[entries]]
id = "57b68994-1c11-43da-991e-6531a2cc725f"
type = "docs"
description = "docusaurus: Update `plugin-content-docs` config for docusarus@beta to not exclude files and folders with underscores."
author = "@chrisstetter"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/235"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/189",
]

[[entries]]
id = "072f60b0-1f4e-4075-a22a-242980b9f555"
type = "hygiene"
description = "remove `MarkdownRenderer.classdef_render_init_signature_if_needed` option because it never worked to begin with"
author = "@NiklasRosenstein"

[[entries]]
id = "f0c733c1-d6db-45ed-a471-3ddd1dc688bb"
type = "breaking change"
description = "remove `MarkdownRenderer.render_to_stream()` from public api"
author = "@NiklasRosenstein"

[[entries]]
id = "56ad7f3e-b0f2-4a96-8066-64249bc18a47"
type = "feature"
description = "add `pydoc_markdown.interfaces.SingleObjectRenderer` and use it in Novella `@pydoc` tag processor"
author = "@NiklasRosenstein"

[[entries]]
id = "ad6ce2db-2342-4baf-8a8d-6f3f858b1ac2"
type = "feature"
description = "add `ApiSuite` class and `ResolverV2` which is used by the new `@pydoc` tag preprocessor when using Novella"
author = "@NiklasRosenstein"

[[entries]]
id = "6bebcee4-6851-4ed6-8600-d0c2b997b97b"
type = "feature"
description = "`MarkdownReferenceResolver` now implements the new `ResolverV2` interface and can resolve references globally"
author = "@NiklasRosenstein"

[[entries]]
id = "1dd5214f-680d-4f36-9c67-19035b0885a0"
type = "feature"
description = "`CrossRefProcessor` now accepts a `resolver_v2` argument to use instead of the `resolver` object passed through the `Processor` API"
author = "@NiklasRosenstein"
